Repository would-you-study-with-me/siksa-clock, pull requests merged in 2022-08, with the labels that each got.

#64 Header , Router생성
  front-end/mona_front/.eslintrc.js
  front-end/mona_front/src/App.tsx
  front-end/mona_front/src/components/common/Header.tsx
  front-end/mona_front/src/routes/AppRoutes.tsx
Labels: 신규기능

#67 버튼 컴포넌트 작업
  front-end/maetdol_front/src/components/Button/Button.component.tsx
  front-end/maetdol_front/src/components/Button/Button.styles.tsx
  front-end/maetdol_front/src/components/Button/index.tsx
  front-end/maetdol_front/src/components/index.tsx
Labels: 신규기능

#70 Create mvp mona
  front-end/mona_front/src/components/common/StarRate.tsx
  front-end/mona_front/src/models/restaurant.model.ts
Labels: 신규기능, 코드리뷰

#72 Mvp maetdol/49 rate component
  front-end/maetdol_front/src/components/StarRate/StarRate.component.tsx
  front-end/maetdol_front/src/components/StarRate/index.ts
  front-end/maetdol_front/src/components/index.tsx
  front-end/maetdol_front/src/utils/index.ts
  front-end/maetdol_front/src/utils/repeat.ts
Labels: 신규기능

#76 Mock 데이터 docker version 0.2
  back-end/docker-compose.yml
  back-end/mvp/Dockerfile
  back-end/mvp/app/main.py
  back-end/mvp/app/models/restaurant.py
  back-end/mvp/app/routers/restaurant.py
  back-end/mvp/app/schemas/restaurant.py
  back-end/mvp/app/services/api_service.py
  back-end/mvp/app/services/main.py
  back-end/mvp/app/services/restaurants.py
  back-end/mvp/poetry.lock
  back-end/mvp/pyproject.toml
  back-end/mvp/requirements.txt
Labels: 신규기능

#80 Dev -> Main Sync
  back-end/docker-compose.yml
  back-end/mvp/Dockerfile
  back-end/mvp/app/main.py
  back-end/mvp/app/models/restaurant.py
  back-end/mvp/app/routers/restaurant.py
  back-end/mvp/app/schemas/restaurant.py
  back-end/mvp/app/services/api_service.py
  back-end/mvp/app/services/main.py
  back-end/mvp/app/services/restaurants.py
  back-end/mvp/poetry.lock
  back-end/mvp/pyproject.toml
  back-end/mvp/requirements.txt
  front-end/mona_front/.eslintrc.js
  front-end/mona_front/src/App.tsx
  front-end/mona_front/src/components/common/Header.tsx
  front-end/mona_front/src/components/common/StarRate.tsx
  front-end/mona_front/src/models/restaurant.model.ts
  front-end/mona_front/src/routes/AppRoutes.tsx
Labels: Sync

#73 홈 mvp 화면 완성
  front-end/mona_front/src/App.tsx
  front-end/mona_front/src/assets/icons/AccountIcon.tsx
  front-end/mona_front/src/assets/icons/BackArrowIcon.tsx
  front-end/mona_front/src/assets/icons/CallIcon.tsx
  front-end/mona_front/src/assets/icons/CloseIcon.tsx
  front-end/mona_front/src/assets/icons/FavoriteIcon.tsx
  front-end/mona_front/src/assets/icons/HomeIcon.tsx
  front-end/mona_front/src/assets/icons/MoodBadIcon.tsx
  front-end/mona_front/src/assets/icons/MoodGoodIcon.tsx
  front-end/mona_front/src/assets/icons/MoodNormalIcon.tsx
  front-end/mona_front/src/assets/icons/PinIcon.tsx
  front-end/mona_front/src/assets/icons/PushPinIcon.tsx
  front-end/mona_front/src/assets/icons/SearchIcon.tsx
  front-end/mona_front/src/assets/icons/SettingIcon.tsx
  front-end/mona_front/src/assets/icons/StarIcon.tsx
  front-end/mona_front/src/assets/icons/StoreIcon.tsx
  front-end/mona_front/src/assets/styles/CustomTheme.tsx
  front-end/mona_front/src/components/card/CardItem.tsx
  front-end/mona_front/src/components/common/Header.tsx
  front-end/mona_front/src/components/common/StarRate.tsx
  front-end/mona_front/src/pages/Home/components/CardList.tsx
  front-end/mona_front/src/pages/Home/index.tsx
Labels: 신규기능

#81 CORS 해결함
  back-end/mvp/app/main.py
  back-end/mvp/app/routers/restaurant.py
Labels: 버그해결

#87 싱크업~!
  front-end/maetdol_front/.eslintrc.js
  front-end/maetdol_front/public/index.html
  front-end/maetdol_front/public/statics/images/icons/AccountIcon.svg
  front-end/maetdol_front/public/statics/images/icons/BackArrowIcon.svg
  front-end/maetdol_front/public/statics/images/icons/Call-Icon.svg
  front-end/maetdol_front/public/statics/images/icons/CloseIcon.svg
  front-end/maetdol_front/public/statics/images/icons/FavoriteIcon.svg
  front-end/maetdol_front/public/statics/images/icons/MainIcon.svg
  front-end/maetdol_front/public/statics/images/icons/MoodBadIcon.svg
  front-end/maetdol_front/public/statics/images/icons/MoodGoodIcon.svg
  front-end/maetdol_front/public/statics/images/icons/MoodNormalIcon.svg
  front-end/maetdol_front/public/statics/images/icons/PinIcon.svg
  front-end/maetdol_front/public/statics/images/icons/PushPinIcon.svg
  front-end/maetdol_front/public/statics/images/icons/SearchIcon.svg
  front-end/maetdol_front/public/statics/images/icons/SettingIcon.svg
  front-end/maetdol_front/public/statics/images/icons/StarIcon.svg
  front-end/maetdol_front/public/statics/images/icons/StoreIcon.svg
  front-end/maetdol_front/src/App.css
  front-end/maetdol_front/src/App.test.tsx
  front-end/maetdol_front/src/App.tsx
  front-end/maetdol_front/src/_types/emotion.d.ts
  front-end/maetdol_front/src/api/request.ts
  front-end/maetdol_front/src/components/Button/Button.component.tsx
  front-end/maetdol_front/src/components/Button/Button.styles.tsx
  front-end/maetdol_front/src/components/Button/index.tsx
  front-end/maetdol_front/src/components/HeaderWithBackButton/HeaderWithBackButton.component.tsx
  front-end/maetdol_front/src/components/HeaderWithBackButton/HeaderWithBackButton.styles.ts
  front-end/maetdol_front/src/components/HeaderWithBackButton/index.ts
  front-end/maetdol_front/src/components/Icon/Icon.component.tsx
  front-end/maetdol_front/src/components/Icon/Icon.hooks.ts
  front-end/maetdol_front/src/components/Icon/Icon.models.ts
  front-end/maetdol_front/src/components/Icon/Icon.styles.ts
  front-end/maetdol_front/src/components/Icon/index.ts
  front-end/maetdol_front/src/components/StarRate/StarRate.component.tsx
  front-end/maetdol_front/src/components/StarRate/index.ts
  front-end/maetdol_front/src/components/index.tsx
  front-end/maetdol_front/src/index.css
  front-end/maetdol_front/src/index.tsx
  front-end/maetdol_front/src/logo.svg
  front-end/maetdol_front/src/reportWebVitals.ts
  front-end/maetdol_front/src/styles/global.ts
  front-end/maetdol_front/src/styles/palette.ts
  front-end/maetdol_front/src/styles/typography.ts
  front-end/maetdol_front/src/utils/index.ts
  front-end/maetdol_front/src/utils/repeat.ts
  front-end/maetdol_front/tsconfig.json
Labels: Sync
