Repository would-you-study-with-me/siksa-clock, pull requests merged in 2022-07, with the labels that each got.

#15 Dev: Front-End Dev Setting
  front-end/.eslintrc.js
  front-end/.gitignore
  front-end/.prettierrc.js
  front-end/README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.test.tsx
  front-end/src/App.tsx
  front-end/src/index.css
  front-end/src/index.tsx
  front-end/src/logo.svg
  front-end/src/react-app-env.d.ts
  front-end/src/reportWebVitals.ts
  front-end/src/setupTests.ts
  front-end/tsconfig.json
Labels: enhancement

#17 기본 MVP 아키텍처 1차 구현
  back-end/mvp/app/config/database.py
  back-end/mvp/app/config/mongo_database.py
  back-end/mvp/app/dependencies.py
  back-end/mvp/app/main.py
  back-end/mvp/app/models/restaurant.py
  back-end/mvp/app/routers/restaurant.py
  back-end/mvp/app/schemas/restaurant.py
  back-end/mvp/app/services/graphql_service.py
  back-end/mvp/app/services/main.py
  back-end/mvp/app/services/restaurants.py
  back-end/mvp/app/services/secret.py
  back-end/mvp/app/test/test_restaurant.py
  back-end/mvp/poetry.lock
  back-end/mvp/pyproject.toml
Labels: enhancement

#30 Mvp maetdol/#27 typography
  front-end/maetdol_front/src/_types/emotion.d.ts
  front-end/maetdol_front/src/styles/typography.ts
Labels: 신규기능

#41 Create mvp mona
  front-end/mona_front/.eslintrc.js
  front-end/mona_front/src/App.css
  front-end/mona_front/src/App.tsx
  front-end/mona_front/src/common/styles/Colors.tsx
  front-end/mona_front/src/common/styles/ThemeProvider.tsx
Labels: 버그해결

#59 아이콘 래퍼 컴포넌트 리뷰 부탁드려요!
  front-end/maetdol_front/src/_types/emotion.d.ts
  front-end/maetdol_front/src/components/Icon/Icon.component.tsx
  front-end/maetdol_front/src/components/Icon/Icon.hooks.ts
  front-end/maetdol_front/src/components/Icon/Icon.models.ts
  front-end/maetdol_front/src/components/Icon/index.ts
  front-end/maetdol_front/src/components/index.tsx
  front-end/maetdol_front/src/styles/palette.ts
Labels: 신규기능

#60 color token, typography 셋업 및 폴더구조 세팅
  front-end/hale_front/.eslintrc.js
  front-end/hale_front/package-lock.json
  front-end/hale_front/src/App.tsx
  front-end/hale_front/src/assets/color.ts
  front-end/hale_front/src/assets/logo.svg
  front-end/hale_front/src/assets/theme.ts
  front-end/hale_front/src/components/RestaurantCard.tsx
  front-end/hale_front/src/pages/Main.tsx
  front-end/hale_front/tsconfig.json
Labels: 신규기능
