Repository would-you-study-with-me/siksa-clock, pull requests merged in 2023-03, with the labels that each got.

#168 카드 컴포넌트 퍼블리싱 마무리~!
  front-end/hale_front/src/assets/color.ts
  front-end/hale_front/src/components/CardTitle.tsx
  front-end/hale_front/src/components/CongestionRate.tsx
  front-end/hale_front/src/components/LocationHeader.tsx
  front-end/hale_front/src/components/RestaurantCard.tsx
  front-end/hale_front/src/components/StarRate.tsx
  front-end/hale_front/src/components/Thumbnail.tsx
  front-end/hale_front/src/components/icons/MoodNormalIcon.tsx
  front-end/hale_front/src/components/icons/StarIcon.tsx
  front-end/hale_front/src/hooks/useMain.hook.ts
  front-end/hale_front/src/model/restaurant-card.interface.ts
  front-end/hale_front/src/pages/Main.tsx
Labels: 신규기능

#183 Feat: 카카오 맵 키, 라우트 base url 변경
  front-end/mona_front/src/assets/const/env_keys.ts
  front-end/mona_front/src/components/card/CardItem.tsx
  front-end/mona_front/src/components/common/Header.tsx
  front-end/mona_front/src/pages/Detail/components/RestaurauntInfo.tsx
  front-end/mona_front/src/routes/AppRoutes.tsx
Labels: 신규기능, 코드리뷰

#186 [#184] FE-build action 체리픽 제대로 안되는 버그 수정
  .github/workflows/build-front-dev.yml
Labels: 버그해결

#181 가게 상세 페이지 퍼블리싱
  front-end/maetdol_front/package-lock.json
  front-end/maetdol_front/package.json
  front-end/maetdol_front/src/App.tsx
  front-end/maetdol_front/src/components/Button/Button.component.tsx
  front-end/maetdol_front/src/components/Button/Button.styles.tsx
  front-end/maetdol_front/src/components/HeaderWithBackButton/HeaderWithBackButton.styles.ts
  front-end/maetdol_front/src/components/HeaderWithSearchAddress/HeaderWithSearchAddress.component.tsx
  front-end/maetdol_front/src/components/HeaderWithSearchAddress/HeaderWithSearchAddress.styles.ts
  front-end/maetdol_front/src/components/RestaurantDetail/index.ts
  front-end/maetdol_front/src/components/Slider/Slider.component.tsx
  front-end/maetdol_front/src/components/Slider/Slider.styles.tsx
  front-end/maetdol_front/src/components/Slider/index.ts
  front-end/maetdol_front/src/components/index.tsx
  front-end/maetdol_front/src/pages/Detail/Detail.page.tsx
  front-end/maetdol_front/src/pages/Detail/Detail.styles.ts
  front-end/maetdol_front/src/pages/Detail/index.ts
  front-end/maetdol_front/src/pages/Home/Home.page.tsx
  front-end/maetdol_front/src/pages/Home/index.ts
  front-end/maetdol_front/src/pages/index.ts
  front-end/maetdol_front/src/routing.tsx
  front-end/maetdol_front/src/styles/global.ts
Labels: 신규기능

#197 카카오 지도 추가
  front-end/maetdol_front/src/App.tsx
  front-end/maetdol_front/src/components/KakaoMap/KakaoMap.component.tsx
  front-end/maetdol_front/src/components/KakaoMap/index.ts
  front-end/maetdol_front/src/components/index.tsx
  front-end/maetdol_front/src/constants/env.constants.ts
  front-end/maetdol_front/src/constants/external-script-url.constants.ts
  front-end/maetdol_front/src/constants/index.ts
  front-end/maetdol_front/src/hooks/externalScript.ts
  front-end/maetdol_front/src/hooks/index.ts
  front-end/maetdol_front/src/pages/Detail/Detail.page.tsx
  front-end/maetdol_front/src/pages/Detail/Detail.styles.ts
Labels: 신규기능

#195 상세페이지 라이브 데이터 추가
  front-end/maetdol_front/package-lock.json
  front-end/maetdol_front/package.json
  front-end/maetdol_front/src/App.tsx
  front-end/maetdol_front/src/components/KakaoMap/KakaoMap.component.tsx
  front-end/maetdol_front/src/components/KakaoMap/index.ts
  front-end/maetdol_front/src/components/Slider/Slider.component.tsx
  front-end/maetdol_front/src/components/index.tsx
  front-end/maetdol_front/src/constants/env.constants.ts
  front-end/maetdol_front/src/constants/external-script-url.constants.ts
  front-end/maetdol_front/src/constants/index.ts
  front-end/maetdol_front/src/hooks/externalScript.ts
  front-end/maetdol_front/src/hooks/index.ts
  front-end/maetdol_front/src/pages/Detail/Detail.hooks.ts
  front-end/maetdol_front/src/pages/Detail/Detail.page.tsx
  front-end/maetdol_front/src/pages/Detail/Detail.styles.ts
  front-end/maetdol_front/src/pages/Home/Home.model.ts
  front-end/maetdol_front/src/pages/Home/Home.utils.ts
  front-end/maetdol_front/tsconfig.json
Labels: 신규기능

#199 상세페이지 리뷰 반영
  front-end/maetdol_front/src/pages/Detail/Detail.hooks.ts
  front-end/maetdol_front/src/pages/Detail/Detail.page.tsx
Labels: 리펙토링
