Repository would-you-study-with-me/siksa-clock, pull requests merged in 2023-02, with the labels that each got.

#158 [Feature] 컴포넌트 명 변경 및 gql 쿼리 분리
  front-end/mona_front/src/hooks/useGetRestaurants.ts
  front-end/mona_front/src/hooks/useGetReverseGeoCoding.ts
  front-end/mona_front/src/pages/Home/components/Home.tsx
  front-end/mona_front/src/pages/Home/index.tsx
Labels: 리펙토링, 코드리뷰

#162 현재 주소 기반으로 레스토랑 받아오도록 수정
  front-end/hale_front/src/hooks/useMain.hook.ts
  front-end/hale_front/src/hooks/useRestaurants.hook.ts
  front-end/hale_front/src/pages/Main.tsx
  front-end/hale_front/src/queries/geocoding.query.ts
Labels: 신규기능

#160 레스토랑 상세 페이지 퍼블리싱!
  front-end/maetdol_front/src/components/RestaurantDetail/RestaurantDetail.component.tsx
  front-end/maetdol_front/src/components/RestaurantDetail/RestaurantDetail.styles.ts
  front-end/maetdol_front/src/components/RestaurantDetail/index.ts
  front-end/maetdol_front/src/styles/global.ts
  front-end/maetdol_front/src/styles/typography.ts
Labels: 리펙토링
